import {MISSIONS,mission,missionOpen,missionWon,type MissionId} from '../game/story'
import type {VillageProfile} from '../game/fixed-store'
import {HEROES,type HeroId} from '../game/heroes'
import type {Difficulty} from '../game/defs'
import {keeperSelector,menuButton as button} from './front-menus'
import {icon} from './icons'
export function campaignScreen(p:VillageProfile,selected:MissionId,hero:HeroId,difficulty:Difficulty,preview:(map:number)=>string,saved:boolean){
 const m=mission(selected)??MISSIONS[0],open=missionOpen(p,m.id),keeper=m.keeper??hero
 return `<div class="campaign-layout"><nav class="campaign-route" aria-label="Campaign missions">${MISSIONS.map((q,i)=>`<button data-action="mission:${q.id}" aria-pressed="${q.id===m.id}" class="${q.id===m.id?'selected':''}"><span>${missionWon(p,q.id)?icon('check'):String(i+1).padStart(2,'0')}</span><div><b>${q.name}</b><small>${missionWon(p,q.id)?'Held':missionOpen(p,q.id)?'Ready to defend':'Complete the previous mission'}</small></div>${!missionOpen(p,q.id)?icon('lock'):''}</button>`).join('')}</nav><article class="campaign-brief"><div class="campaign-chart">${preview(m.map)}<span>${m.waves.length} waves</span></div><div class="campaign-copy"><h3>${m.name}</h3><p class="lead">${m.brief}</p><p class="resident-line">“${m.line}”<small>${m.resident}</small></p><div class="campaign-reward"><span>Bring back</span><b>${m.reward}</b></div>${m.keeper?`<p class="small muted">${HEROES[keeper].name} guides this first watch. Sparks and Chimes, then your first held pulse.</p>`:keeperSelector(hero,'story-hero')}<div class="segmented" aria-label="Difficulty">${(['relaxed','standard','nightfall'] as const).map(d=>`<button data-action="story-mode:${d}" aria-pressed="${difficulty===d}" class="${difficulty===d?'selected':''}">${d==='relaxed'?'Gentle':d==='standard'?'Standard':'Nightfall'}</button>`).join('')}</div>${saved?'<p class="menu-save-note">Beginning replaces your saved campaign watch. District progress and expeditions are kept.</p>':''}${open?button('story-begin:'+m.id,missionWon(p,m.id)?'Defend again':'Begin mission','primary wide'):'<p class="notice">Complete the previous mission to open this waterway.</p>'}</div></article></div><p class="campaign-other">${button('expeditions','Expeditions')}${button('choose','Long watches & endurance')}</p>`
}
